### ISSUE TITLE
Accepting sgRNAs with length != 20

### ISSUE THREAD

**Issue by joshdempster** [cancerdatasci/ceres#2]
Currently, CERES assumes that sgRNAs have 20 nts before the PAM in the function `guideAlignments`. However, some libraries use 19 nt guides. Ideally this could be solved by taking the alignment end rather than the beginning for positive strand alignments.  Simple hack that worked for me instead: add an argument `guide_length` to the `guideAlignments` call signature. `guide_length` can be determined in `map_guide_to_locus` by checking the number of characters in the first entry in `guides` (assumes all guides are the same length).

**Comment by j-g-b** [comment]
Thanks Josh!
