### ISSUE TITLE
Error message in example data run: Could not locate a Bowtie index 

### ISSUE THREAD

**Issue by romanos-sp** [cancerdatasci/ceres#3]
Hello, 
I ran into this error message
```
 prepare_ceres_inputs(inputs_dir=gecko_inputs_dir,
+                      dep_file=gecko_dep_file,
+                      cn_seg_file=cn_seg_file,
+                      gene_annot_file=gene_annot_file,
+                      rep_map_file=gecko_rep_map,
+                      chromosomes=paste0("chr", 1:22),
+                      dep_normalize="zmad")
loading dependency data...

Parsed with column specification:
cols(
  Replicate = col_character(),
  CellLine = col_character()
)
loading copy number data...

|======================================================| 100%   43 MB
mapping sgRNAs to the genome...

Could not locate a Bowtie index corresponding to basename "hg19"
Overall time: 00:00:00
Command: /usr/local/Cellar/bowtie/1.2.2_p1/bin/bowtie-align-s --wrapper basic-0 -t -p 4 -a -v 0 -f -S hg19 /var/folders/1t/gz_zw2bx635fyxqplq1ttb6c0000gp/T//RtmpYoJMLF/guides.fa /var/folders/1t/gz_zw2bx635fyxqplq1ttb6c0000gp/T//RtmpYoJMLF/guides.sam 
[E::hts_open_format] Failed to open file /var/folders/1t/gz_zw2bx635fyxqplq1ttb6c0000gp/T//RtmpYoJMLF/guides.sam
samtools view: failed to open "/var/folders/1t/gz_zw2bx635fyxqplq1ttb6c0000gp/T//RtmpYoJMLF/guides.sam" for reading: No such file or directory
Error in value[[3L]](cond) : 
  failed to open BamFile: file(s) do not exist:
  '/var/folders/1t/gz_zw2bx635fyxqplq1ttb6c0000gp/T//RtmpYoJMLF/guides.bam'
```

I have downloaded hg19_bowtie.tar and placed it unzipped in the bowtie_indexes folder of example_data. 

Thanks!

**Comment by j-g-b** [comment]
Have you set your BOWTIE_INDEXES environmental variable with Sys.setenv(BOWTIE_INDEXES = file.path(data_dir, "bowtie_indexes"))?

If you have and are still running into this error, try pointing the environmental variable to "bowtie_indexes/hg19".

If that fails, then as a hack you can change your working directory to the folder containing the index files (e.g. "bowtie_indexes/hg19") and try running the prepare inputs function from there. 

To be honest, I've had mixed success with bowtie finding the index files properly and have had to resort to all of the above methods at various times.

**Comment by romanos-sp** [comment]
It didn't work. 

I setwd'd to example_data, moved the hg19_bowtie.tar file there, along with the rest of the files, redirected everything accordingly, but I still got the same error message.

**Comment by j-g-b** [comment]
Sorry if this is what you already tried, but did you run the command from within the hg19 directory where the .ebwt files are located? See this post for clarification: http://seqanswers.com/forums/showthread.php?t=3977

If that doesn't work then I have to assume the problem can be solved by properly orienting

**Comment by j-g-b** [comment]
Hoping this worked? If not let me know and I can troubleshoot more

**Comment by romanos-sp** [comment]
It worked! Thanks!
