### ISSUE TITLE
Error "Failed connect to ftp.ncbi.nlm.nih.gov:21"

### ISSUE THREAD

**Issue by mavershang** [cancerdatasci/ceres#5]
I kept gettting the following error when running the prepare_ceres_inputs with the example data

> Error in function (type, msg, asError = TRUE)  :
>   Failed connect to ftp.ncbi.nlm.nih.gov:21; Connection timed out

Any suggestion?

**Comment by yesitsjess** [comment]
I get the same. I'm also not entirely clear why it needs to connect to this ncbi?
Error in function (type, msg, asError = TRUE)  : 
  Failed connect to ftp.ncbi.nlm.nih.gov:21; Connection refused

**Comment by yesitsjess** [comment]
Ensure you're connected to the internet. You might need to set your proxy using `Sys.setenv(http_proxy="http://proxy:port")` but make sure you replace http://proxy:port with the right proxy information
